name: ssh-to-remote-server
on: 
  push:
    branches:
      - main
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest #using latest ubuntu to build application
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
            cd ~/ustream
            export PATH=$PATH:/home/waqar/.nvm/versions/node/v21.6.0/bin/pm2
            source ~/.bashrc
            pm2 status
            
